apache/pekko-sbt-paradox

- .asf.yaml
> Add settings to asf.yaml

- plugin/plugins.sbt
> Add sbt-scalafmt

- .asf.yaml
Makes sure that you can't merge PR if code is unformatted
> Add strict check that code is formatted

- .asf.yaml
Judging from another project I maintain I think this should be correct version?
> Fix scalafmt check context

- plugin/plugins.sbt
- project/plugins.sbt
> fix scalafmt plugin

- README.md
As mentioned here https://github.com/apache/incubator-pekko/issues/92#issue-1523977563
> Document how to use plugin under JDK 1.8

- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
* Github repository
* Copyright text
Fixes #13
> add settings for some customization options

- README.md
> Fix Akka mention in README.md

- build.sbt
- project/plugins.sbt
> Add Apache to POM licenses field by updating sbt-apache-sonatype

- build.sbt
- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
- theme/src/main/assets/assets/javascripts/groups.js
- theme/src/main/assets/assets/javascripts/paradox-material-theme.js
- theme/src/main/assets/assets/stylesheets/pekko-theme.css
- theme/src/main/assets/page.st
Not quite ideal to have to copy so much stuff from underlying projects but we will likely have to do that anyway for other customizations.
Refs #25, https://github.com/jonas/paradox-material-theme/issues/11
> make groups work with material plugin

- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
As suggested in https://github.com/apache/incubator-pekko/discussions/214
> use simpler color scheme to increase contrast of logo against header bar

- theme/src/main/assets/assets/stylesheets/pekko-theme.css
- theme/src/main/assets/page.st
- theme/src/main/assets/partials/extra_nav_links.st
- theme/src/main/assets/partials/nav.st
> added some general apache links to the nav bar

- .gitignore
- theme/src/main/assets/partials/extra_nav_links.st
> add extra ASF links

- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
* based on https://issues.apache.org/jira/browse/LEGAL-634
> change web site copyright

- build.sbt
- project/plugins.sbt
Replaces ci-release with dynver, see https://lists.apache.org/thread/l7yp8yb2ooy7opwmzpw7hkmz9gm0qr2r
> Replace ci-release with dynver

- theme/src/main/assets/partials/footer.st
Copies this file - https://github.com/jonas/paradox-material-theme/blob/2d57fe0567ea9fe7e8de14faef4fa777841d505a/theme/src/main/assets/partials/footer.st#L68 - but removes that one line
fix for https://github.com/apache/incubator-pekko-sbt-paradox/issues/42
> remove powered-by by overriding footer.st

- .github/workflows/publish.yml
- project/AddMetaInfLicenseFiles.scala
- project/build.properties
* also update ci job to use better supported way to install java
> add disclaimer to jar

- README.md
needed for the release of this component - so voters have some basic instructions
> add build instructions to README

- README.md
- build.sbt
- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
- project/plugins.sbt
- theme/src/main/assets/partials/extra_nav_links.st
a few build files for our web pages that are missing the header
> add ASL header to some files

- LICENSE
found as part of voting for release
> add missing link to file in LICENSE

- theme/src/main/assets/assets/stylesheets/pekko-theme.css
https://lists.apache.org/thread/9hsxs5hpz9g2fgcbq9k590glprg40rs4
> add ASL header to css

- .asf.yaml
Now that we are making proper releases we shouldn't be merging PR's that don't have reviews (not that we were doing this but its good to have a proper check for this like we have on other projects).
> Add in review check

- build.sbt
> Add sensible scalac options

- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
> Make settings lazy val

- README.md
The current instructions are out of date
> Update README.md to note new JDK usage instructions

- README.md
See https://github.com/apache/incubator-pekko-connectors/pull/537 for context
> Document excludesAll for additional sbt-paradox plugins
