- .asf.yaml
So I can confirm that the status check is now properly defined which means it should no longer make the `main` branch stuck.
You can verify this by looking at this PR https://github.com/apache/incubator-pekko-sbt-paradox/pull/6. Currently `main` only has the scalafmt status check enabled for the `test` branch and that PR does a PR against that `test` branch.
I also verified that the check fails if the code isn't formatted by deliberately committing unformatted code and it works as expected
> Enable scalafmt status check for main

- build.sbt
Reverts apache/incubator-pekko-sbt-paradox#16
This revealed that the NEXUS credentials are empty.
> Revert "try to debug publishing issue"

- build.sbt
- project/plugins.sbt
Uses the sbt-apache-sonatype plugin instead of manually setting up the Apache sonatype settings. Additionally also adds the `DISCLAIMER` in `META-INF` just like other projects.
> Use sbt-apache-sonatype

- build.sbt
- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
- plugin/src/main/scala/org/apache/pekko/SearchIndex.scala
That avoids problems with an old, incompatible circe version used in the parent paradox-material-theme by not calling the offending code any more.
Refs #34
> use spray-json for search index creation

- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
We might not want to use it everywhere.
(Also it eats up into the visitor's Github Api quota heavily because of the way it is implemented...)
> make Github repository link optional

- build.sbt
- project/plugins.sbt
Updates to latest version of sbt-apache-sonatype. Note that `organization` is no longer needed, sbt-apache-sonatype sets this up for you.
> Updates sbt-apache-sonatype

- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
relates to https://issues.apache.org/jira/browse/LEGAL-634 - we need to acknowledge Lightbend copyright because they wrote most of the site contents but we don't need to assert an ASF copyright
> remove ASF copyright

- theme/src/main/assets/page.st
relates to https://github.com/apache/incubator-pekko-sbt-paradox/issues/53
ASF do not want us to download fonts from Google (we can host them ourselves if we have to) or for us to use Google Analytics.
I built pekko-http docs locally with this change and the web site looks the same.
> disallow google analytics and google fonts

- theme/src/main/assets/assets/stylesheets/pekko-theme.css
Quite subtle:
but will light up when source is hovered:
Fixes #38.
> Fix snippet buttons to fit material style

- theme/src/main/assets/assets/javascripts/groups.js
Before these were accidentally converted into tabs as well as the content was lost.
E.g. https://nightlies.apache.org/pekko/docs/pekko-http/main-snapshot/docs/introduction.html#the-modules-that-make-up-apache-pekko-http
> fix definition lists

- LICENSE
- plugin/src/main/scala/org/apache/pekko/SearchIndex.scala
- theme/src/main/assets/assets/javascripts/paradox-material-theme.js
- theme/src/main/assets/page.st
- theme/src/main/assets/partials/footer.st
- theme/src/main/assets/partials/nav.st
* key aim is to keep the original headers without any mods
* add some extra comment lines afterwards, adding more context
* add full MIT license for paradox-material-theme to our LICENSE
* see comments inline
> update license headers

- theme/src/main/assets/assets/javascripts/groups.js
The context of this discussion is https://lists.apache.org/thread/bh1vqjnf7vjzyzhgbcv979g0hl6dly0s . The intent of the PR is just make the wording of the referenced docs ultra clear i.e. the code on this page is **NOT** derived or copied from MDN, rather the links are there as references in case you want more information on how cookies work.
> Better clarify documentation references

- theme/src/main/assets/partials/extra_nav_links.st
The old link is now redirecting to https://www.apache.org/foundation/sponsors
It seems tidier to link to the new link.
> change thanks link

- .github/workflows/format.yml
- .github/workflows/publish.yml
The latest version of the checkout github actions now supports a `fetch-tags` flag which does as described, i.e. it will fetch all of our tags which removes the various workarounds that was used before (i.e. manually running `git fetch` command) etc etc, see https://github.com/actions/checkout/pull/579
This will also help in the erroneous errors that we get in CI, i.e. 
```
[error] Failed to derive version from git tags. Maybe run `git fetch --unshallow` or `git fetch upstream` on a fresh git clone from a fork? Derived version: 0.0.0+1-337943bd-SNAPSHOT`
```
> Use fetch tags from latest checkout action

- theme/src/main/assets/page.st
- theme/src/main/assets/partials/nav.st
Refs: https://github.com/apache/incubator-pekko-site/issues/33
Then we can hidden page versioning on "top-level-page" of Pekko website, and still display by default for other project, all those stuff can switch via configuration.
set it by specifying the flag in `build.sbt`
```
paradoxProperties += ("disabled.versioning.display" -> "true")
```
> feat: Support configurable display of version

- theme/src/main/assets/assets/stylesheets/pekko-theme.css
This PR add styling for tables in paradox. The goal is to display the tables in the docs more clearly.
> Adding styling for tables in paradox

- theme/src/main/assets/page.st
Adding a dedicated stylesheet option to the page layout to support dedicated styling for pages.
> Adding a dedicated  stylesheet to the page layout

- LICENSE
- build.sbt
- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
- plugin/src/main/scala/org/apache/pekko/SearchIndex.scala
- project/plugins.sbt
- theme/src/main/assets/page.st
- theme/src/main/assets/partials/footer.st
- theme/src/main/assets/partials/nav.st
See https://github.com/sbt/sbt-paradox-material-theme/issues/59
> Use sbt-paradox-material-theme 0.7.0

- build.sbt
As documented it doesn't make sense for this project to depend on sbt-pekko-build just for the inliner settings since sbt-pekko-build is defined for core pekko modules which are intended for users where was this project is only intended for pekko use.
Once we can make release artifacts in CI this will be greatly simplified.
> Add inliner settings

- build.sbt
- project/plugins.sbt
Same as in 
- https://github.com/apache/incubator-pekko-http/pull/486
- https://github.com/apache/incubator-pekko/pull/1135
> Use sbt-web 1.5.x despite staying on paradox 0.9.2

- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
- theme/src/main/assets/partials/footer.st
Resolves: https://github.com/apache/incubator-pekko-sbt-paradox/issues/115
Trying this with pekko core, this is what it looks like with this change (there should be no difference in rendered text)
And when setting `pekkoParadoxIncubatorNotice` to `None`
> Make incubator notice optional

- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
> Make single arg defs lazy val's

- build.sbt
With this change I can confirm replacing
https://github.com/apache/incubator-pekko-http/blob/main/project/plugins.sbt#L25-L37
with
```scala
addSbtPlugin("org.apache.pekko" % "pekko-sbt-paradox" % "1.0.1-RC1+2-dbf8082e+20240303-1152-SNAPSHOT")
```
works properly (I just tried locally)
> Exclude dependencies for sbt-paradox-apidoc/sbt-paradox-project-info

- README.md
> Better clarify excludeAll statement

- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
Now that pekko is out of incubator we can set the default value to `None` for the next time round a release happens.
> Set pekkoParadoxIncubatorNotice to None

- plugin/src/main/scala/org/apache/pekko/PekkoParadoxPlugin.scala
`in` notation has been deprecated in sbt
> remove old sbt config style

- .github/workflows/ci.yml
- .github/workflows/clean.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
If and when we do a new release of this sbt plugin and our other projects uptake it, they will then not be able with Java 8 because some of the downstream plugins need newer versions of Java.
> upgrade dependencies
